language: python

python:
  - "3.4"
  - "3.5"
  - "3.6"
#  - "3.5-dev" # 3.5 development branch
#  - "nightly" # currently points to 3.6-dev

sudo: required

env:
  - PLUGIN=
  - PLUGIN=octave-interval
  - PLUGIN=ValidatedNumerics.jl

before_install:
  -
    if [ "$PLUGIN" == "octave-interval" ]; then
      sudo add-apt-repository --yes ppa:octave/stable;
      sudo apt-get update -qq;
      sudo apt-get install -qq -y octave liboctave-dev libmpfr-dev;
    fi

  -
    if [ "$PLUGIN" == "ValidatedNumerics.jl" ]; then
      sudo add-apt-repository --yes ppa:staticfloat/juliareleases;
      sudo add-apt-repository --yes ppa:staticfloat/julia-deps;
      sudo apt-get update -qq;
      sudo apt-get install -qq julia;
    fi

install:
  - pip install .

  -
    if [ "$PLUGIN" == "octave-interval" ]; then
      octave -q --no-gui --eval "pkg install -forge interval";
    fi

  -
    if [ "$PLUGIN" == "ValidatedNumerics.jl" ]; then
      julia -q --eval 'Pkg.add("ValidatedNumerics")';
      julia -q --eval 'Pkg.add("FactCheck")';
    fi

script:
  -
    if [ "$PLUGIN" == "" ]; then
      python -m itf1788 -s itl -o output;
    fi

  -
    if [ "$PLUGIN" == "octave-interval" ]; then
      python -m itf1788 -s itl -o output -c "(octave, native, interval)";
      make -C output/octave/native/interval;
    fi

  -
    if [ "$PLUGIN" == "ValidatedNumerics.jl" ]; then
      python -m itf1788 -s itl -o output -c "(julia, *, ValidatedNumerics)";
      make -C output/julia/Base.Test/ValidatedNumerics;
      make -C output/julia/FactCheck/ValidatedNumerics;
    fi
