language: python

python:
  - "3.4"
  - "3.5"
  - "3.6"
#  - "3.5-dev" # 3.5 development branch
#  - "nightly" # currently points to 3.6-dev

sudo: false

# Also run the generated tests for particular libraries
matrix:
  include:
    - env: ARITH=octave-interval
      sudo: required
    - env: ARITH=ValidatedNumerics.jl TEST=Base.Test
      sudo: required
    - env: ARITH=ValidatedNumerics.jl TEST=FactCheck
      sudo: required

before_install:
  -
    if [ "$ARITH" == "octave-interval" ]; then
      sudo add-apt-repository --yes ppa:octave/stable;
      sudo apt-get update -qq;
      sudo apt-get install -qq -y octave liboctave-dev libmpfr-dev;
    fi

  -
    if [ "$ARITH" == "ValidatedNumerics.jl" ]; then
      sudo add-apt-repository --yes ppa:staticfloat/juliareleases;
      sudo add-apt-repository --yes ppa:staticfloat/julia-deps;
      sudo apt-get update -qq;
      sudo apt-get install -qq julia;
    fi

install:
  - pip install .

  -
    if [ "$ARITH" == "octave-interval" ]; then
      octave -q --no-gui --eval "pkg install -forge interval";
    fi

  -
    if [ "$ARITH" == "ValidatedNumerics.jl" ]; then
      julia -q --eval 'Pkg.add("ValidatedNumerics")';
      if [ "$TEST" == "FactCheck" ]; then
        julia -q --eval 'Pkg.add("FactCheck")';
      fi
    fi

script:
  -
    if [ "$ARITH" == "" ]; then
      python -m itf1788 -s itl -o output;
    fi

  -
    if [ "$ARITH" == "octave-interval" ]; then
      python -m itf1788 -s itl -o output -c "(octave, native, interval)";
      make -C output/octave/native/interval;
    fi

  -
    if [ "$ARITH" == "ValidatedNumerics.jl" ]; then
      python -m itf1788 -s itl -o output -c "(julia, $TEST, ValidatedNumerics)";
      make -C output/julia/$TEST/ValidatedNumerics;
    fi
